### ISSUE TITLE
Brainstorm: dismissing custom notices

### ISSUE THREAD

**Issue by JasonTheAdams** [stellarwp/admin-notices#4]
Something I'd like to make even easier in this library is the ability to dismiss custom notices. This is technically currently possible to be done programmatically, using the `window.stellarwp.adminNotices.dismissNotice()` function. However this means that custom JS has to be written, which a goal of this library is to make unnecessary for notices — though the function is certainly worth keeping for real complex situations.

I'd like to use classes and/or attributes to make it possible for someone to create custom notice markup, and simply add the appropriate markup, which the library JS will pick up on and handle. We may also add some methods to `AdminNotice` to potentially wrap the notice in styleless markup to accomplish this.

I've also heard it mentioned that it might be useful to support dismissing a single notice to actually hide multiple nodes within the DOM. I consider that a secondary objective, however it may be worth having in mind when considering this.

The purpose of this Issue is to brainstorm this topic and arrive at an API we like!

**Comment by JasonTheAdams** [comment]
The idea I've had so far is to use a combination of a class and an attribute that can be added to the markup. The class would be on the node (likely a button) that triggers the closing. The attribute would be there to identify the ID of the notification, and potentially the top-most parent node so the notification can be hidden.

Something like:
```html
<div data-stellarwp-namespace-notice-id="my-custom-notice">
    <span class="js-stellarwp-namespace-close-notice">X</span>
    <div>
        <h2>Notice</h2>
        <p>Notice content</p>
    </div>
</div>
```

Of note:
- `data-stellarwp-{namespace}-notice-id` on the container with the id
- `js-stellarwp-{namespace}-close-notice` on the "X" which the user clicks

I'm tempted that, by default, we would use [$(node).fadeOut](https://api.jquery.com/fadeOut/) to hide the notice — exactly like how the standard WP notices are hidden. If we don't want this to be the behavior, perhaps adding an alternative class could be `js-stellarwp-{namespace}-mark-notice-closed`, which marks it closed but doesn't actually hide the notice.

**Comment by JasonTheAdams** [comment]
If we go the container route, then we could potentially add a `withCustomWrapper()` method that wraps whatever is rendered in the `<div>` with the attribute and id.

Tangentially, we could have a `withPlacementWrapper()` method as well, which adds support for `.notice` and `.inline` classes to also assist in notice placement. If both methods are used, it sticks to just a single wrapping div with the appropriate attribute/classes. 🤔

**Comment by stratease** [comment]
> The idea I've had so far is to use a combination of a class and an attribute that can be added to the markup. The class would be on the node (likely a button) that triggers the closing. The attribute would be there to identify the ID of the notification, and potentially the top-most parent node so the notification can be hidden.
> 
> Something like:
> 
> ```
> <div data-stellarwp-namespace-notice-id="my-custom-notice">
>     <span class="js-stellarwp-namespace-close-notice">X</span>
>     <div>
>         <h2>Notice</h2>
>         <p>Notice content</p>
>     </div>
> </div>
> ```
This is how I'd go. 

I'd also add some JS events for people to leverage if they want something very particular.

**Comment by stratease** [comment]
I'd consider on the `AdminNotice` something along the lines of `$notice->addClass('some-custom-class')` or `$notice->addAttribute('data-some-custom', 'toggle_id');`

**Comment by nikolaystrikhar** [comment]
I like this approach and @stratease's suggestion.

**Comment by JasonTheAdams** [comment]
I've been working on a PR for this, and I'd like to get some thoughts from folks.

So WordPress is interesting in the way that it positions notices in the admin. It doesn't actually care where in the DOM the notice is placed. Instead, is uses JS to look for the `.notice` class (and `.notice-inline`), and then moves it to its respective position. The same thing is true of the close button. It looks for `.notice-dismiss` and then adds the button via JS. It's useful from a PHP perspective but odd.

It's a reasonable scenario to imagine that folks will want to display a custom notice (e.g. #6) in a standard location. What's tricky is that the `.notice` class, which tells WP where to put it, also applies the standard CSS styles.

I've initially gone down the road of thinking in "wrappers" — the literal HTML wrapping the notice content. Presently there's a `$notice->withWrapper()` that's true by default; custom notices can apply `withoutWrapper()`. But in light of the this issue, which looks for an attribute and close class, I thought to add `withCustomWrapper()`. To get things into location, I played with `withLocationWrapper()`. It starts to look weird:

```php
AdminNotices::show('custom', '<div>My custom notice</div>')
	->withCustomWrapper()
	->withLocationWrapper()
```

I don't love that. It also doesn't address the problem that the "location wrapper" class of `.notice` still adds styling. Ugh:

<img width="429" alt="image" src="https://github.com/user-attachments/assets/741fb2bd-4119-4c1a-8084-ec3550db756b">

I have a couple ideas I'd love some thoughts on:

## Cleaner API
First, I'd like to drop the whole "wrapper" thing, or at least make it something that's rarely needed. Perhaps we just make the assumption that there's _always_ a wrapper to add things like the ID attribute, and then potentially other classes — but the focus is on what it does, not what wrapper or its markup. I'm imagining a couple new methods:

```php
// The standard wrapper, location, etc.
AdminNotice::show('standard', 'My standard WP location');

// The wrapper only has the id attribute and is in the standard location
AdminNotice::show('custom', 'My custom notice')
	->custom();

// Is custom and is in the inline location
AdminNotice::show('custom_inline', 'Custom and inline')
	->custom()
	->inline();

// Is custom and does not relocate
AdminNotice::show('custom_in_place', 'Custom and not re-located')
	->custom()
	->inPlace()

// The same as above, auto applying inPlace(), but the more likely scenario for notices in custom locations
AdminNotice::render('custom_rendered_in_place', 'Custom and rendered in-place')
	->custom()
```
